# Generated by Django 5.1.3 on 2024-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurdApp', '0003_rename_studnet_results_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='computer_science',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='english',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='islmyast',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='pak_study',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='urdu',
            field=models.IntegerField(default=100),
        ),
    ]
