# Generated by Django 5.0.4 on 2024-12-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurdApp', '0004_alter_student_computer_science_alter_student_english_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=200)),
                ('employe_dep', models.CharField(max_length=200)),
                ('employe_age', models.CharField(max_length=200)),
                ('employe_address', models.CharField(max_length=200)),
            ],
        ),
    ]
